# Generated by Django 4.0.6 on 2022-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
